---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Check installed plugins
  shell: >
    {{ kibana_plugins_bin }} list | sed 's/@.*//' | grep -v '^$' 2>/dev/null
  when: >
    kibana_plugins | length > 0
  register: kibana_plugins_installed_results
  changed_when: false
  failed_when: false

- name: Install plugins
  shell: >
    {{ kibana_plugins_bin }} install {{ item }}
  when: >
    item[0] != '!' and
    kibana_plugins | length > 0 and (
      kibana_plugins_installed_results is not defined or
      item not in kibana_plugins_installed_results.stdout_lines
    )
  with_items: "{{ kibana_plugins }}"
  notify:
    - restart kibana

